app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	
	path('sports/', views.SportsView.as_view(), name='sports'),
	path('health/', views.HealthView.as_view(), name='health'),
	path('books/', views.BooksView.as_view(), name='books'),
	path('men_fashion/', views.MFashionView.as_view(), name='men_fashion'),
	path('women_fashion/', views.WFashionView.as_view(), name='women_fashion'),
	path('kids/', views.KidsView.as_view(), name='kids'),
	path('electronics/', views.ElectronicsView.as_view(), name='electronics'),
	path('privacypolicy/', views.PrivacypolicyView.as_view(), name='privacypolicy'),
	path('termsofuse/', views.TermsofuseView.as_view(), name='termsofuse'),
	path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
	path('contactus/', views.ContactUsView.as_view(), name='contactus'),
	
	
	path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('search/', views.SearchView.as_view(), name='search'),
	
	
]
  

marketreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
	path('signup/', views.SignupView.as_view(), name='signup'),	
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.shortcuts import render, reverse
from django.conf import settings

CATEGORY_CHOICES = (
    ('S', 'Sports'),
    ('H', 'Health & Beauty'),
    ('B', 'Books'),
	('MF', 'Men Fashion'),
	('WF', 'Women Fashion'),
	('PH', 'Phones & Tablets'),
	('K', 'Kids & Babies'),
	('L', 'Laptops & PCs')
)

LABEL_CHOICES = (
	('A', ''),
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1,)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField()
    image2 = models.ImageField(default="blank")
    image3 = models.ImageField(default="blank")
    image4 = models.ImageField(default="blank")
    Buy_url = models.TextField(default='#')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
       return reverse("app:product", kwargs = {'slug': self.slug})
	   

app/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username', 'email', 'password')

        def clean(self):
        	cleaned_data = super(UserForm, self).clean()
        	password = cleaned_data.get("password")
        	confirm_password = cleaned_data.get("confirm_password")

        	if password != confirm_password:
        	    raise forms.ValidationError("password and confirm_password does not match")

app/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import View, DetailView, ListView
from .models import Item
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from .forms import UserForm

class IndexView(View):
	def get(self, request):
		all = Item.objects.all()
		new = all[0::-1]

		if len(new) > 7:
			new = new[0:8]
		else:
			new = new[0:]

		popular = Item.objects.filter(label='P')
		contex = {'all':all,
				  'popular':popular,
				  'new':new
				}
		return render(request, "app/index.html", contex )


class SportsView(View):
	def get(self, request):
		popular = Item.objects.filter(label='P',category='S')
		Items = Item.objects.filter(category='S')
		new = Item.objects.filter(label='S', category='S')
		return render(request, "app/sports.html", {
		'popular':popular,
		'Items':Items,
		'new':new
		})

class HealthView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='H')
		return render(request, "app/health.html", {"Items":Items})

class BooksView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='B')
		return render(request, "app/books.html", {"Items":Items})

class MFashionView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='MF')
		return render(request, "app/men_fashion.html", {"Items":Items})

class PhonesTabletsView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='PH')
		return render(request, "app/phonestablets.html", {"Items":Items})

class WFashionView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='WF')
		return render(request, "app/women_fashion.html", {"Items":Items})

class KidsView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='K')
		return render(request, "app/kids.html", {"Items":Items})

class CamerasView(View):
	def get(self, request):
		
		Items = Item.objects.filter(category='CM')
		return render(request, "app/cameras.html", {"Items":Items})

class ElectronicsView(View):
	def get(self, request):
	
		Items = Item.objects.filter(category='E')
		return render(request, "app/electronics.html", {"Items":Items})

class PrivacypolicyView(View):
	def get(self, request):
		return render(request, "app/privacypolicy.html")

class TermsofuseView(View):
	def get(self, request):
		return render(request, "app/termsofuse.html")

class AboutUsView(View):
	def get(self, request):
		return render(request, "app/aboutus.html")
		
class ContactUsView(View):
	def get(self, request):
		return render(request, "app/contactus.html")
				
				
class ItemDetailView(DetailView):
    model = Item
    template_name = "app/product.html"
	
	
class SearchView(ListView):

	def get(self, request):
		all = Item.objects.all() 
		search = request.GET.get("search_title")
		category = request.GET.get("category")

		
		if search != '' and search is not None:
			all = all.filter(title__icontains=search)
			
		if category != '' and category is not None:
			all = all.filter(category__icontains=category)

		contex = {'all':all}

		return render(request, "app/search.html", contex )

class SignupView(View):
	form_class = UserForm
	template_name = 'registration/signup.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			
			user.set_password(password)
			user.save()

			# if Credential are correct
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('app:index')
		return render(request, self.template_name, {'form':form})

app/templates/app/books.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Books</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}

app/templates/app/cameras.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Cameras</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}

app/templates/app/electronics.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Electronics</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}

app/templates/app/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <!--div class="pb-4">

      <a href="https://www.facebook.com/" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

    </div-->
    <!-- Social icons -->

<a href="/termsofuse" >Terms of use  -  </a>
<a href="/privacypolicy" >Privacy Policy  -  </a>
<a href="/aboutus" >About Us  -  </a>
<a href="/contactus" >Contact Us </a>

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2020 Copyright:
      
    </div>
    <!--/.Copyright-->

</footer>

app/templates/app/health.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Health & Beauty</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}
 {% load bootstrap4 %}
 {% bootstrap_css %}
 {% bootstrap_javascript jquery='full' %}
 {% bootstrap_messages %}
 

{% block extra_content %}

<div class="row" style="margin-top:80px;">
<div  id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="15000">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
 
	<div class="carousel-item active">
      <img src="{% static 'img/demo1_1920x600.jpg' %}" class="d-block w-100" alt="...">
    </div>
	 

    <div class="carousel-item ">
      <img src="{% static 'img/demo2_1920x600.jpg' %}" class="d-block w-100" alt="...">
    </div>
	
	<div class="carousel-item ">
      <img src="{% static 'img/RE4wEaN (Custom).jpg' %}" class="d-block w-100" alt="...">
    </div>


  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
{% endblock %}


{% block content %}
 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
 

    <style>
	
	.breaker h1 {
		width: 100%; 
		text-align: center;
		color:gray;
		border-bottom: 0.5px solid #ccc; 
		line-height: 0.1em;
		margin: 10px 0 20px;
	  } 

	.breaker h1 span { 
		font-family: 'Tangerine', serif;
		background:#fff; 
		padding:0 10px; 
		color:#74B6C7;

	  }
	h5 {
		color:skyblue;
	
	}
	
	.category-padding{ 
		padding:10px;
	
	}

    </style>
	
 
<div class="container">
<div class="row">


<div class="col-12" >

<div class="card mt-5" style="">
  <div class="card-body">
<!-- BREAKER (Popular) -->

	<div class="breaker" style="padding:10px">
		<h1><span>Popular</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->



<div class="row" style="padding:10px">
<div id="popularslider" class="carousel slide pb-3" data-ride="carousel">
  <div class="carousel-inner">

			<div class="carousel-item active"> 
			  <div class="row"> 

		{% for item in popular %}
			<div class="col-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top">{% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
						  {% if item.discount_price %}
						  
							  <span class="mr-1">
								<del style="color:gray;" >${{ item.price }}</del>
							  </span>
							  
							  <span>${{ item.discount_price }}</span>
							  
							  {% else %}
							  <span style="font-weight:bold;">${{ item.price }}</span>
						  {% endif %}
                  </strong>
                </h4>
				
				<h5>

					  {% if item.get_label_display == "danger" %}
							<span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
					  {% elif item.get_label_display == "primary" %}
						    <span class="badge badge-pill {{ item.get_label_display }}-color">Best seller</span>
					  {% else %}
							<span style="color:white;">A</span>
					  {% endif %}

				</h5>
				
              </div>
				<a class="card-footer text-center" href="{{ item.get_absolute_url }}" style="text-decoration: none;" >
					<strong class="text-muted" >QUICK REVIEW</strong>
				</a>
            </div>

          </div>

				{% if forloop.counter|divisibleby:3 and not forloop.last %}
				</div>
			</div>

			<div class="carousel-item">
			    <div class="row">
				{% endif %}
		{% endfor %}
			    </div>
			</div>
		
  </div>
  
   <a class="carousel-control-prev" href="#popularslider" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#popularslider" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  
</div>
</div>


<!-- BREAKER (NEW) -->

<div class="breaker" style="padding:50px 0;">
	<h1><span>New Arrivals</span></h1>
</div>

<!-- BREAKER (NEW) /-->


<div class="row" style="padding:10px">
<div id="Newslider" class="carousel slide " data-ride="carousel" data-interval="8000">
  <div class="carousel-inner">

			<div class="carousel-item active"> 
			  <div class="row"> 

				{% for item in new %}
			<div class="col-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top">{% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
              {% if item.discount_price %}
              <span class="mr-1">
                <del style="color:gray;" >${{ item.price }}</del>
              </span>
              <span>${{ item.discount_price }}</span>
              {% else %}
              <span style="font-weight:bold;">${{ item.price }}</span>
              {% endif %}
                  </strong>
                </h4>
				<h5>


					  {% if item.get_label_display == "danger" %}
							<span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
					  {% elif item.get_label_display == "primary" %}
						    <span class="badge badge-pill {{ item.get_label_display }}-color">Best seller</span>
					  {% else %}
							<span style="color:white;">A</span>
					  {% endif %}

				</h5>
              </div>
				<a class="card-footer text-center" href="{{ item.get_absolute_url }}" style="text-decoration: none;" >
					<strong class="text-muted" >QUICK REVIEW</strong>
				</a>
            </div>

          </div>

				{% if forloop.counter|divisibleby:3 and not forloop.last %}
				</div>
			</div>

			<div class="carousel-item">
			    <div class="row">
				{% endif %}
			{% endfor %}
			    </div>
			</div>
		
  </div>
  
   <a class="carousel-control-prev" href="#Newslider" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#Newslider" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  
</div>
</div>


<!-- BREAKER (ALL) -->

<div class="breaker" style="padding:50px 0;">
	<h1><span>All Categories</span></h1>
</div>

<!-- BREAKER (ALL) /-->

<div class="row">
<div class="col-4 category-padding">

<a href="electronics/" >

	<div class="card bg-dark text-white">
	  <img src="{% static '/img/electronics (Custom).jpg' %}" class="card-img" alt="...">
	  <div class="card-img-overlay">

		<p class="card-text"></p>
		<p class="card-text"></p>
	  </div>
	</div>
	
</a>

</div>

<div class="col-4 category-padding">

<a href="health/" >

	<div class="card bg-dark text-white">
	  <img src="{% static '/img/health (Custom).jpg' %}" class="card-img" alt="...">
	  <div class="card-img-overlay">

		<p class="card-text"></p>
		<p class="card-text"></p>
	  </div>
	</div>
	
</a>

</div>

<div class="col-4 category-padding">

<a href="sports/" >

	<div class="card bg-dark text-white">
	  <img src="{% static '/img/sports.jpg' %}" class="card-img" alt="...">
	  <div class="card-img-overlay">

		<p class="card-text"></p>
		<p class="card-text"></p>
	  </div>
	</div>
	
</a>

</div>


		

<div class="col-4 category-padding">

<a href="men_fashion/" >

	<div class="card bg-dark text-white">
	  <img src="{% static '/img/men.jpg' %}" class="card-img" alt="...">
	  <div class="card-img-overlay">

		<p class="card-text"></p>
		<p class="card-text"></p>
	  </div>
	</div>
	
</a>

</div>

<div class="col-4 category-padding">

<a href="kids/" >

	<div class="card bg-dark text-white">
	  <img src="{% static 'img/baby (Custom).png' %}" class="card-img" alt="...">
	  <div class="card-img-overlay">

		<p class="card-text"></p>
		<p class="card-text"></p>
	  </div>
	</div>
	
</a>

</div>


<div class="col-4 category-padding">

<a href="women_fashion/" >

	<div class="card bg-dark text-white">
	  <img src="{% static '/img/svg/GuaLz93-woman-icon-vector.svg' %}" class="card-img" alt="...">
	  <div class="card-img-overlay">

		<p class="card-text"></p>
		<p class="card-text"></p>
	  </div>
	</div>
	
</a>

</div>


</div>

</div>


</div>
</div>

	<!-- Users posts -->

<!--'start'  div class="col-4 mt-5">


<div class="card " style="width: 17rem;">
    <div class="card-header">
		<h5 class="card-title text-center mt-2" ><strong>Users articles</strong></h5>
	</div>
  <div class="card-body">


	
<div class="card my-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-4">
      <img src="{% static 'img/1.jpg' %}" style="max-width:150px; max-height:150px;" class="card-img" alt="...">
    </div>
    <div class="col-8">
        <p style="padding:5px;" class="card-text">This is a wider card with supporting text below card  </p>
    </div>
  </div>
</div>

<div class="card my-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-4">
      <img src="{% static 'img/1.jpg' %}" style="max-width:150px; max-height:150px;" class="card-img" alt="...">
    </div>
    <div class="col-8">
        <p style="padding:5px;" class="card-text">This is a wider card with supporting text below card  </p>
    </div>
  </div>
</div>

<div class="card my-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-4">
      <img src="{% static 'img/1.jpg' %}" style="max-width:150px; max-height:150px;" class="card-img" alt="...">
    </div>
    <div class="col-8">
        <p style="padding:5px;" class="card-text">This is a wider card with supporting text below card  </p>
    </div>
  </div>
</div>

<div class="card my-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-4">
      <img src="{% static 'img/1.jpg' %}" style="max-width:150px; max-height:150px;" class="card-img" alt="...">
    </div>
    <div class="col-8">
        <p style="padding:5px;" class="card-text">This is a wider card with supporting text below card  </p>
    </div>
  </div>
</div>

<div class="card my-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-4">
      <img src="{% static 'img/1.jpg' %}" style="max-width:150px; max-height:150px;" class="card-img" alt="...">
    </div>
    <div class="col-8">
        <p style="padding:5px;" class="card-text">This is a wider card with supporting text below card  </p>
    </div>
  </div>
</div-->


	<!-- Users posts /          'finish'-->


  </div>
</div>
</div>

</div>
</div>
{% endblock %}

app/templates/app/kids.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Kids & Babies</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}

app/templates/app/phonestablets.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Phones & Tablets</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}

app/templates/app/privacypolicy.html
{% extends 'app/base.html' %}

{% block content %}



{% endblock %}

app/templates/app/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

app/templates/app/search.html
{% extends 'app/base.html' %}

{% block content %}
<style>
.breaker h1 {
	width: 100%; 
	text-align: center;
	color:gray;
	border-bottom: 0.5px solid #ccc; 
	line-height: 0.1em;
	margin: 10px 0 20px;
} 

.breaker h1 span { 
	font-family: 'Tangerine', serif;
	background:#fff; 
	padding:0 10px; 
	color:#74B6C7;
}
	  

</style>

<div style="margin-top:150px;"></div>


<form   class="form-inline justify-content-center" method="GET" action="/search/">

		<select id="category" class="form-control" name="category">
			<option value="">Categories</option>
			<option value="S" >Sports</option>
			<option value="H" >Health & Beauty</option>
			<option value="B" >Books</option>
			<option value="MF" >Men Fashion</option>	
			<option value="PH" >Phones & Tablets</option>
			<option value="WF" >Women Fashion</option>
			<option value="K" >Kids & Babies</option>
			<option value="L" >Laptops & PCs</option>	
		</select>
		

			<input  id="searching" class="form-control mr-sm-2" type="search" name="search_title" placeholder="Search..." aria-label="Search">
			<button class="btn btn-sm btn-outline-primary my-2 my-sm-0" type="submit">Search</button>

</form>

<!-- BREAKER (Search result) -->

<div class="breaker" style="padding:50px 0;">
	<h1><span>Search result</span></h1>
</div>

<!-- BREAKER (Search result) /-->

<div class="row">

{% for item in all %}
	  
        <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top">{% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
              {% if item.discount_price %}
              <span class="mr-1">
                <del style="color:gray;" >${{ item.price }}</del>
              </span>
              <span>${{ item.discount_price }}</span>
              {% else %}
              <span style="font-weight:bold;">${{ item.price }}</span>
              {% endif %}
                  </strong>
                </h4>
				<h5>
				
					  {% if item.get_label_display == "danger" %}
							<span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
					  {% elif item.get_label_display == "primary" %}
						    <span class="badge badge-pill {{ item.get_label_display }}-color">Best seller</span>
					  {% else %}
							<span style="color:white;">A</span>
					  {% endif %}

				</h5>
              </div>
				<a class="card-footer text-center" href="{{ item.get_absolute_url }}" style="text-decoration: none;" >
					<strong class="text-muted" >QUICK REVIEW</strong>
				</a>
            </div>

          </div>
			  <!--a href="{% url 'app:product' item.slug %}" ><img src="{{item.image.url}}"  class="d-block w-100"  alt="..."></a-->


{% endfor %}
</div>


{% endblock %}

app/templates/app/women_fashion.html
{% extends 'app/categories_base.html' %}
{% load static %}

   {% block category_content %}
   
   <!-- BREAKER (Popular) -->

	<div class="breaker" style=" padding:50px;">
		<h1><span>Women Clothing</span></h1>
	</div>
	
<!-- BREAKER (Popular) -->

   
   {% endblock %}